import { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import useFetch from '../hooks/useFetch';
import { Repository } from '../types/github';
import ProjectTicker from '../components/ProjectTicker';

const Home: NextPage = () => {
	const repos = useFetch<Repository[]>('/api/github');

	return (
		<div className={styles.container}>
			<Head>
				<title>Hello World!</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<section id='intro'>
					<h1>Hello World!</h1>
					<p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
				</section>

				<section id='github-project'>
					{!!repos.isLoading ? (
						<p>Loading...</p>
					) : (
						/*(
						<ProjectTicker projects={repos.data!} />
					)*/ <></>
					)}
				</section>
			</main>
		</div>
	);
};

export default Home;
