import { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import useFetch from '../hooks/useFetch';
import { Repository } from '../types/github';

const Home: NextPage = () => {
	const repos = useFetch<Repository[]>('/api/github');

	return (
		<div className={styles.container}>
			<Head>
				<title>Hello World!</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<h1>Hi babe!</h1>
			{!!repos.isLoading ? (
				<p>Loading...</p>
			) : (
				<main>
					<ul>
						{repos.data!.map(repo => {
							return <li key={repo.id}>{repo.name}</li>;
						})}
					</ul>
				</main>
			)}
		</div>
	);
};

export default Home;
